### ISSUE TITLE
One command to start app

### ISSUE THREAD

**Issue by samporapeli** [athenekilta/oloscreen-v2#9]
Currently 3 different things need to be started. It would be better if only one command would start everything.

**Comment by KasperNurminen** [comment]
Tähän voisi tehdä vaan shell-skriptin jossa luetellaan allekkain vaaditut komennot. Tän shell-skriptin vois sitten heittää crontabiin tyylillä

`@reboot tähän/polku/start-everything.sh`

**Comment by samporapeli** [comment]
This is currently being solved by dockerizing Oloscreen

**Comment by samporapeli** [comment]
Solved by #43
